name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Configura o SSH para autenticação
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout do repositório atual
        uses: actions/checkout@v3

      - name: Clonar o repositório para deploy na Azure
        run: |
          git config --global user.name "Jansem Wallemberg"
          git config --global user.email "jansemwall@gmail.com"
          git remote add target-repo git@github.com:JansemWall/STE.git
          git push target-repo main --force
