name: Sync

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Configuração do SSH para autenticação
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout do repositório atual
        uses: actions/checkout@v3

      - name: Clone do repositório para deploy na Azure
        run: |
          git config --global user.name "JansemWall"
          git config --global user.email "jansemwall@gmail.com"
          git clone --bare git@github.com:ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-2-e5-proj-empext-t5-pmv-ads-2024-2-e5-ste.git
          cd pmv-ads-2024-2-e5-proj-empext-t5-pmv-ads-2024-2-e5-ste.git
          git push --mirror git@github.com:JansemWall/STE.git
          cd ..
          rm -rf pmv-ads-2024-2-e5-proj-empext-t5-pmv-ads-2024-2-e5-ste.git
